### ISSUE TITLE
Group capstone - Kanban Board

### ISSUE THREAD

**Issue by Becky449** [oyhpnayiaw-as-micronaut/ruby_capstone#17]
- Our group is made of three members @Becky449, @oyhpnayiaw  and @Chaseknis .
- The project link is https://github.com/orgs/oyhpnayiaw-as-micronaut/projects/3.
- Team member 1 tasks are assigned @Chaseknis 
- Team member 2 tasks are assigned to @oyhpnayiaw 
- Team member 3 tasks are assigned to @Becky449

**Comment by PinkMoon25** [comment]
Hi @Becky449 @oyhpnayiaw @Chaseknis , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Kanban template :heavy_check_mark: 
Required columns :heavy_check_mark: 
all tasks assigned :heavy_check_mark: 
distributed fairly :heavy_check_mark: 

## Required Changes ♻️

- [ ] Hi team, great work so far, just one small thing your group task has no points mentioned in the card, please specify the point for this task just like you have done for the others, **the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work.**

## Optional suggestions

- [ ] [OPTIONAL] I think it will be better if you separate the group tasks into multiple cards at least two one for the item class and one for the main.rb file, it wll give more clarity
- [ ] [OPTIONAL]  Also I would suggest to create a separate card for creating the schema.sql file, as currently it is under the preserve data task card which is a bit out of context as both of them are seperate tasks :+1: 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by KDlamini** [comment]
### Hi @Becky449 @oyhpnayiaw @Chaseknis 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes for the Ruby Kanban Board Project Setup. 🎊 🥳 
Your feature is complete!
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ The big tasks are split into smaller tasks 
✔️ There's proper time allocation to each task
✔️ All team members are allocated a task
✔️ Each task has a description and a task title

# Status: Approved ✔️ 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by oyhpnayiaw** [comment]
1.
